* About
  This file is a collection of configurations and scripts for Emacs, i3, zsh.
  
  This actually constitutes my current laptop environement for daily use. Any feedback or help in improving it will be warmly welcomed!

  To use this file, you have to tangle all source code blocks inside their respective file, specified in the =:tangle= attributes of source blocks or of subtrees' properties. The easiest way is to open this file in emacs with org-mode, and use =C-c C-v t= key to export all code blocks at once.
* Organization
  - Codes/ :: main projects
  - Hacks/ :: some minor projects
  - Scripts/ :: useful scripts for every day use
  - Tests/ :: temporary code, for quick tests
  - Datasets/ :: collection of data and datasets

* Random wallpaper generation
  :PROPERTIES:
  :header-args: :tangle ~/.generate_wallpaper.sh
  :END:
  Bash script for generating wallpaper with random quotes appearing with transparency on a random background image. The quotes should be inside a file, separated by line breaks.
  1. Script settings
     #+BEGIN_SRC bash
       WALLPAPERS_PATH="~/.wallpapers/"
       QUOTE_PATH="~/.quotes.txt"
       OUTPUT_PATH="~/.wallpaper.png"
     #+END_SRC
  2. Choose random background image inside =.wallpapers=
     #+BEGIN_SRC bash
       random_background=$WALLPAPERS$(ls $WALLPAPERS_PATH | sort -R | head -1)
     #+END_SRC
  3. Choose random text from list of aphorisms
     #+BEGIN_SRC bash
       random_quote=$(cat $QUOTE_PATH | sort -R | head -1)
     #+END_SRC
  4. Generate wallpaper
     #+BEGIN_SRC bash
       convert -pointsize 200  -fill "rgba(0,0,0,0.4)" -draw "text 270,460 \"${random_quote}\"" ${random_background} $OUTPUT_PATH
     #+END_SRC
  6. Finally, you can use feh for displaying the newly generated wallpaper (I use it inside my i3 configuration)
* Applications and scripts
** LINE messenger on desktop
   Install chromium, chrome or brave.
   Then install the LINE app.
   Then find how to access it.
   Then use this code:
   #+BEGIN_SRC bash
#!/bin/bash
# Run LINE as a standalone
brave --app=chrome-extension://ophjlpahpchlmihnnnihgmmeilfjmjjc/index.html
   #+END_SRC
